#!/usr/bin/env bash
set -euo pipefail

REPO_URL="${CDXM_INSTALL_REPO_URL:-https://github.com/lucianlamp/codex-monitor}"
REF="${CDXM_INSTALL_REF:-main}"
INSTALL_ROOT="${CDXM_INSTALL_ROOT:-$HOME/.codex-monitor}"
BIN_DIR="$INSTALL_ROOT/bin"
SKILL_DIR="${CDXM_SKILL_DIR:-$HOME/.codex/skills/codex-monitor}"
AGENTS_BIN="${CDXM_AGENTS_BIN:-$HOME/.agents/bin}"
SHIM_TARGET="$AGENTS_BIN/codex"

ASSUME_YES=0
INSTALL_SHIM=""
UPDATE_PATH=""
SKIP_BUILD=0
SOURCE_DIR=""
TMP_DIR=""

usage() {
  cat <<'EOF'
Usage: install.sh [options]

Installs codex-monitor for daily use:
  - cdxm and codex-monitor binaries under ~/.codex-monitor/bin
  - the Codex skill under ~/.codex/skills/codex-monitor
  - an optional Codex CLI shim at ~/.agents/bin/codex

Options:
  --yes             Accept default yes prompts for binary, skill, and PATH.
  --install-shim    Install the Codex shim if ~/.agents/bin/codex is absent.
  --no-shim         Skip Codex shim installation.
  --no-path         Do not update shell PATH files.
  --source <path>   Use a local codex-monitor checkout instead of downloading.
  --skip-build      Do not run cargo install. Useful for installer tests.
  --help            Show this help.

The installer never overwrites an existing ~/.agents/bin/codex.
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --yes|-y)
      ASSUME_YES=1
      shift
      ;;
    --install-shim)
      INSTALL_SHIM=1
      shift
      ;;
    --no-shim)
      INSTALL_SHIM=0
      shift
      ;;
    --no-path)
      UPDATE_PATH=0
      shift
      ;;
    --source)
      SOURCE_DIR="${2:?--source requires a path}"
      shift 2
      ;;
    --skip-build)
      SKIP_BUILD=1
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

cleanup() {
  if [ -n "$TMP_DIR" ]; then
    rm -rf "$TMP_DIR"
  fi
}
trap cleanup EXIT

prompt_yes_no() {
  local prompt="$1"
  local default="$2"
  local answer suffix

  if [ "$ASSUME_YES" -eq 1 ]; then
    case "$default" in
      y|Y) return 0 ;;
      *) return 1 ;;
    esac
  fi

  case "$default" in
    y|Y) suffix="[Y/n]" ;;
    *) suffix="[y/N]" ;;
  esac

  if [ -r /dev/tty ] && [ -w /dev/tty ]; then
    printf '%s %s ' "$prompt" "$suffix" >/dev/tty
    IFS= read -r answer </dev/tty || answer=""
  else
    answer=""
  fi

  answer="${answer:-$default}"
  case "$answer" in
    y|Y|yes|YES|Yes) return 0 ;;
    *) return 1 ;;
  esac
}

repo_from_script_dir() {
  local self="${BASH_SOURCE[0]:-}"
  local dir
  if [ -n "$self" ] && [ -f "$self" ]; then
    dir="$(cd "$(dirname "$self")" && pwd)"
    if [ -f "$dir/Cargo.toml" ] && [ -d "$dir/skills/codex-monitor" ]; then
      printf '%s\n' "$dir"
      return 0
    fi
  fi
  return 1
}

download_source() {
  local archive_url="$REPO_URL/archive/refs/heads/$REF.tar.gz"
  TMP_DIR="$(mktemp -d)"
  echo "Downloading codex-monitor from $archive_url"
  curl -fsSL "$archive_url" | tar -xz -C "$TMP_DIR"
  find "$TMP_DIR" -maxdepth 1 -type d -name "codex-monitor-*" | head -1
}

resolve_source_dir() {
  if [ -n "$SOURCE_DIR" ]; then
    (cd "$SOURCE_DIR" && pwd)
    return 0
  fi
  if repo_from_script_dir; then
    return 0
  fi
  download_source
}

shell_quote() {
  printf '%q' "$1"
}

install_binaries() {
  if [ "$SKIP_BUILD" -eq 1 ]; then
    mkdir -p "$BIN_DIR"
    echo "Skipped cargo install (--skip-build)."
    return 0
  fi

  if ! command -v cargo >/dev/null 2>&1; then
    echo "cargo is required to build codex-monitor from source." >&2
    echo "Install Rust/Cargo, then rerun this installer." >&2
    exit 1
  fi

  mkdir -p "$INSTALL_ROOT"
  cargo install --path "$SOURCE_DIR" --bins --force --root "$INSTALL_ROOT"
  echo "Installed cdxm to $BIN_DIR/cdxm"
}

install_skill() {
  local source_skill="$SOURCE_DIR/skills/codex-monitor"
  if [ ! -d "$source_skill" ]; then
    echo "missing skill source: $source_skill" >&2
    exit 1
  fi
  mkdir -p "$(dirname "$SKILL_DIR")"
  rm -rf "$SKILL_DIR"
  cp -R "$source_skill" "$SKILL_DIR"
  chmod +x "$SKILL_DIR"/scripts/*.sh 2>/dev/null || true
  echo "Installed Codex skill to $SKILL_DIR"
}

shim_kind() {
  local path="$1"
  if [ ! -f "$path" ]; then
    echo "missing"
  elif grep -q "CODEX_MONITOR_SHIM_WRAPPER=1" "$path" 2>/dev/null; then
    echo "codex-monitor"
  elif grep -Eq "AGMSG_CODEX_SHIM_WRAPPER|agmsg monitor mode|codex-shim.sh" "$path" 2>/dev/null; then
    echo "agmsg"
  else
    echo "custom-or-unknown"
  fi
}

write_codex_shim() {
  mkdir -p "$AGENTS_BIN"
  if [ -e "$SHIM_TARGET" ]; then
    local kind
    kind="$(shim_kind "$SHIM_TARGET")"
    echo "$SHIM_TARGET already exists: detected $kind; leaving existing codex entrypoint untouched."
    return 0
  fi

  local run_dir_default
  run_dir_default="$HOME/Library/Caches/codex-monitor/shim"

  {
    cat <<'SHIM_HEAD'
#!/usr/bin/env bash
set -euo pipefail

# Codex monitor shim. Generated by codex-monitor install.sh.
# CODEX_MONITOR_SHIM_WRAPPER=1
export CODEX_MONITOR_SHIM_WRAPPER=1

resolve_real_codex() {
  if [ -n "${CODEX_MONITOR_REAL_CODEX:-}" ]; then
    printf '%s\n' "$CODEX_MONITOR_REAL_CODEX"
    return 0
  fi

  local self_dir self_path shim_target old_ifs path_dir candidate candidate_dir candidate_path
  self_dir="$(cd "$(dirname "$0")" && pwd)"
  self_path="$self_dir/$(basename "$0")"
  shim_target="${CODEX_MONITOR_SHIM_TARGET:-$self_path}"

  old_ifs="$IFS"
  IFS=:
  for path_dir in $PATH; do
    IFS="$old_ifs"
    [ -n "$path_dir" ] || path_dir="."
    candidate="$path_dir/codex"
    if [ -x "$candidate" ]; then
      candidate_dir="$(cd "$(dirname "$candidate")" 2>/dev/null && pwd || true)"
      [ -n "$candidate_dir" ] || continue
      candidate_path="$candidate_dir/$(basename "$candidate")"
      if [ "$candidate_path" != "$self_path" ] && [ "$candidate_path" != "$shim_target" ]; then
        printf '%s\n' "$candidate_path"
        return 0
      fi
    fi
    IFS=:
  done
  IFS="$old_ifs"

  echo "codex-monitor shim: real codex not found on PATH" >&2
  return 1
}

project_from_args() {
  local project="$PWD"
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --cd|--cwd|-C)
        if [ "$#" -gt 1 ]; then
          project="$2"
          shift 2
          continue
        fi
        ;;
      --cd=*|--cwd=*)
        project="${1#*=}"
        shift
        continue
        ;;
    esac
    shift
  done
  if [ -d "$project" ]; then
    (cd "$project" && pwd)
  else
    printf '%s\n' "$PWD"
  fi
}

first_non_option() {
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --cd|--cwd|-C)
        shift 2 || true
        ;;
      --cd=*|--cwd=*)
        shift
        ;;
      --help|--version|-h|-V)
        printf '%s\n' "$1"
        return 0
        ;;
      --*)
        shift
        ;;
      -*)
        shift
        ;;
      *)
        printf '%s\n' "$1"
        return 0
        ;;
    esac
  done
  return 1
}

hash_project() {
  if command -v shasum >/dev/null 2>&1; then
    printf '%s' "$1" | shasum | awk '{print $1}'
  else
    printf '%s' "$1" | cksum | awk '{print $1}'
  fi
}

port_alive() {
  (exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null
}

ensure_app_server() {
  local real_codex="$1"
  local project="$2"
SHIM_HEAD
    printf '  local run_dir="${CODEX_MONITOR_SHIM_RUN_DIR:-%s}"\n' "$(shell_quote "$run_dir_default")"
    cat <<'SHIM_TAIL'
  local project_hash server_log server_pid port_file existing_port existing_pid port

  project_hash="$(hash_project "$project")"
  mkdir -p "$run_dir"
  server_log="$run_dir/codex-app-server.$project_hash.log"
  server_pid="$run_dir/codex-app-server.$project_hash.pid"
  port_file="$run_dir/codex-app-server.$project_hash.port"

  port=""
  if [ -f "$port_file" ] && [ -f "$server_pid" ]; then
    existing_port="$(cat "$port_file" 2>/dev/null || true)"
    existing_pid="$(cat "$server_pid" 2>/dev/null || true)"
    if [ -n "$existing_port" ] && [ -n "$existing_pid" ] \
      && kill -0 "$existing_pid" 2>/dev/null && port_alive "$existing_port"; then
      port="$existing_port"
    fi
  fi

  if [ -z "$port" ]; then
    : > "$server_log"
    "$real_codex" app-server --listen "ws://127.0.0.1:0" >>"$server_log" 2>&1 &
    echo "$!" > "$server_pid"
    for _ in $(seq 1 100); do
      port="$(sed -n 's#.*listening on: ws://127\.0\.0\.1:\([0-9][0-9]*\).*#\1#p' "$server_log" | head -1)"
      [ -n "$port" ] && break
      sleep 0.1
    done
    if [ -z "$port" ]; then
      echo "codex-monitor shim: app-server did not report a listening port" >&2
      echo "codex-monitor shim: see $server_log" >&2
      exit 1
    fi
    printf '%s' "$port" > "$port_file"
  fi

  if ! port_alive "$port"; then
    echo "codex-monitor shim: app-server did not start on ws://127.0.0.1:$port" >&2
    echo "codex-monitor shim: see $server_log" >&2
    exit 1
  fi
  printf 'ws://127.0.0.1:%s' "$port"
}

real_codex="$(resolve_real_codex)"

if [ "${CODEX_MONITOR_SHIM_DISABLE:-}" = "1" ]; then
  exec "$real_codex" "$@"
fi

command_name="$(first_non_option "$@" || true)"
case "$command_name" in
  app-server|exec|login|logout|mcp|completion|debug|apply|review|sandbox|help|--help|-h|version|--version|-V)
    exec "$real_codex" "$@"
    ;;
esac

project="$(project_from_args "$@")"
socket_url="$(ensure_app_server "$real_codex" "$project")"

case "$command_name" in
  resume)
    monitor_args=()
    removed_resume=0
    for arg in "$@"; do
      if [ "$removed_resume" -eq 0 ] && [ "$arg" = "resume" ]; then
        removed_resume=1
        continue
      fi
      monitor_args+=("$arg")
    done
    cd "$project"
    exec "$real_codex" resume --remote "$socket_url" "${monitor_args[@]}"
    ;;
  *)
    cd "$project"
    exec "$real_codex" --remote "$socket_url" "$@"
    ;;
esac
SHIM_TAIL
  } > "$SHIM_TARGET"
  chmod +x "$SHIM_TARGET"
  echo "Installed Codex monitor shim to $SHIM_TARGET"
}

update_path_file() {
  local path_entry="$1"
  local rc_file="$HOME/.zshrc"
  local marker_begin="# >>> codex-monitor PATH >>>"
  local marker_end="# <<< codex-monitor PATH <<<"
  mkdir -p "$(dirname "$rc_file")"
  if [ -f "$rc_file" ] && grep -qF "$marker_begin" "$rc_file"; then
    echo "PATH entry already managed in $rc_file"
    return 0
  fi
  {
    printf '\n%s\n' "$marker_begin"
    printf 'export PATH="%s:$PATH"\n' "$path_entry"
    printf '%s\n' "$marker_end"
  } >> "$rc_file"
  echo "Added $path_entry to PATH in $rc_file"
}

SOURCE_DIR="$(resolve_source_dir)"
if [ ! -f "$SOURCE_DIR/Cargo.toml" ]; then
  echo "source does not look like codex-monitor: $SOURCE_DIR" >&2
  exit 1
fi

echo "codex-monitor installer"
echo "source: $SOURCE_DIR"
echo "binary root: $INSTALL_ROOT"
echo "skill dir: $SKILL_DIR"
echo "codex shim target: $SHIM_TARGET"

if prompt_yes_no "Install cdxm and codex-monitor binaries to $BIN_DIR?" y; then
  install_binaries
else
  echo "Skipped binary install."
fi

if prompt_yes_no "Install Codex skill to $SKILL_DIR?" y; then
  install_skill
else
  echo "Skipped skill install."
fi

if [ -z "$INSTALL_SHIM" ]; then
  if prompt_yes_no "Install Codex shim at $SHIM_TARGET?" n; then
    INSTALL_SHIM=1
  else
    INSTALL_SHIM=0
  fi
fi

if [ "$INSTALL_SHIM" = "1" ]; then
  write_codex_shim
else
  echo "Skipped Codex shim install."
fi

if [ -z "$UPDATE_PATH" ]; then
  if prompt_yes_no "Add $BIN_DIR and $AGENTS_BIN to PATH in ~/.zshrc?" y; then
    UPDATE_PATH=1
  else
    UPDATE_PATH=0
  fi
fi

if [ "$UPDATE_PATH" = "1" ]; then
  update_path_file "$BIN_DIR"
  update_path_file "$AGENTS_BIN"
else
  echo "Skipped PATH update."
fi

echo ""
echo "Done."
echo "Open a new shell or run: source ~/.zshrc"
echo "Then verify:"
echo "  command -v cdxm"
echo "  type -a codex"
