[CmdletBinding()]
param(
    [switch]$Yes,
    [switch]$InstallShim,
    [switch]$NoShim,
    [switch]$NoPath,
    [string]$Source,
    [switch]$SkipBuild,
    [string]$RepoUrl = $(if ($env:CDXM_INSTALL_REPO_URL) { $env:CDXM_INSTALL_REPO_URL } else { 'https://github.com/lucianlamp/codex-monitor' }),
    [string]$Ref = $(if ($env:CDXM_INSTALL_REF) { $env:CDXM_INSTALL_REF } else { 'main' }),
    [string]$InstallRoot = $(if ($env:CDXM_INSTALL_ROOT) { $env:CDXM_INSTALL_ROOT } else { Join-Path $HOME '.codex-monitor' }),
    [string]$SkillDir = $(if ($env:CDXM_SKILL_DIR) { $env:CDXM_SKILL_DIR } else { Join-Path $HOME '.codex\skills\codex-monitor' }),
    [string]$AgentsBin = $(if ($env:CDXM_AGENTS_BIN) { $env:CDXM_AGENTS_BIN } else { Join-Path $HOME '.agents\bin' })
)

$ErrorActionPreference = 'Stop'

$BinDir = Join-Path $InstallRoot 'bin'
$ShimTarget = Join-Path $AgentsBin 'codex.cmd'
$TempDir = $null

function Confirm-CdxmStep {
    param(
        [string]$Prompt,
        [bool]$DefaultYes
    )

    if ($Yes) {
        return $DefaultYes
    }

    $suffix = if ($DefaultYes) { '[Y/n]' } else { '[y/N]' }
    $answer = Read-Host "$Prompt $suffix"
    if ([string]::IsNullOrWhiteSpace($answer)) {
        return $DefaultYes
    }
    return $answer -match '^(y|yes)$'
}

function Resolve-CdxmSource {
    if ($Source) {
        return (Resolve-Path $Source).Path
    }

    if ($PSScriptRoot -and
        (Test-Path (Join-Path $PSScriptRoot 'Cargo.toml')) -and
        (Test-Path (Join-Path $PSScriptRoot 'skills\codex-monitor'))) {
        return $PSScriptRoot
    }

    $script:TempDir = Join-Path ([IO.Path]::GetTempPath()) ("codex-monitor-" + [Guid]::NewGuid().ToString('N'))
    New-Item -ItemType Directory -Force -Path $script:TempDir | Out-Null
    $zip = Join-Path $script:TempDir 'codex-monitor.zip'
    $archiveUrl = "$RepoUrl/archive/refs/heads/$Ref.zip"
    Write-Host "Downloading codex-monitor from $archiveUrl"
    Invoke-WebRequest -Uri $archiveUrl -OutFile $zip
    Expand-Archive -Path $zip -DestinationPath $script:TempDir -Force
    $sourceDir = Get-ChildItem -Path $script:TempDir -Directory |
        Where-Object { $_.Name -like 'codex-monitor-*' } |
        Select-Object -First 1
    if (-not $sourceDir) {
        throw "Downloaded archive did not contain a codex-monitor source directory"
    }
    return $sourceDir.FullName
}

function Install-CdxmBinaries {
    param([string]$SourceDir)

    New-Item -ItemType Directory -Force -Path $BinDir | Out-Null
    if ($SkipBuild) {
        Write-Host "Skipped cargo install (-SkipBuild)."
        return
    }

    $cargo = Get-Command cargo -ErrorAction SilentlyContinue
    if (-not $cargo) {
        throw "cargo is required to build codex-monitor from source. Install Rust/Cargo, then rerun this installer."
    }

    Write-Host "Note: Windows native agmsg SQLite support uses bundled rusqlite and requires the Rust MSVC toolchain plus MSVC Build Tools."
    & cargo install --path $SourceDir --bins --force --root $InstallRoot
    if ($LASTEXITCODE -ne 0) {
        throw "cargo install failed with exit code $LASTEXITCODE"
    }
    Write-Host "Installed cdxm to $(Join-Path $BinDir 'cdxm.exe')"
}

function Install-CdxmSkill {
    param([string]$SourceDir)

    $sourceSkill = Join-Path $SourceDir 'skills\codex-monitor'
    if (-not (Test-Path $sourceSkill)) {
        throw "missing skill source: $sourceSkill"
    }

    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $SkillDir) | Out-Null
    if (Test-Path $SkillDir) {
        Remove-Item -Recurse -Force $SkillDir
    }
    Copy-Item -Recurse -Force $sourceSkill $SkillDir
    Write-Host "Installed Codex skill to $SkillDir"
}

function Get-CodexEntrypointKind {
    param([string]$Path)

    if (-not (Test-Path $Path)) {
        return 'missing'
    }
    $content = Get-Content -Path $Path -Raw -ErrorAction SilentlyContinue
    if ($content -match 'CODEX_MONITOR_SHIM_WRAPPER=1') {
        return 'codex-monitor'
    }
    if ($content -match 'AGMSG_CODEX_SHIM_WRAPPER|agmsg monitor mode|codex-shim') {
        return 'agmsg'
    }
    return 'custom-or-unknown'
}

function Write-CdxmCodexCmd {
    # The Windows codex.cmd is a thin launcher that runs the shared bash shim
    # (skills/codex-monitor/scripts/codex-shim.sh) through Git Bash, so the
    # routing logic stays identical to macOS/Linux instead of being a separate
    # PowerShell reimplementation.
    $shimSource = Join-Path $SkillDir 'scripts\codex-shim.sh'
    if (-not (Test-Path $shimSource)) {
        throw "codex shim script not found at $shimSource; install the codex-monitor skill before the shim."
    }
    $shimBashPath = '/' + $shimSource.Substring(0, 1).ToLower() + ($shimSource.Substring(2) -replace '\\', '/')

    $cmd = @"
@echo off
rem codex-monitor shim (Windows) -- generated by codex-monitor install.ps1.
rem Routes codex through Git Bash into the shared bash shim
rem (skills/codex-monitor/scripts/codex-shim.sh) so behavior matches macOS/Linux.
set "WINPTY_SPAWNED=1"
set "CODEX_MONITOR_SHIM_WRAPPER=1"
set "CODEX_MONITOR_SHIM_TARGET=%~f0"
set "CDXM_BASH=%CDXM_GIT_BASH%"
if "%CDXM_BASH%"=="" set "CDXM_BASH=%GIT_BASH%"
if "%CDXM_BASH%"=="" set "CDXM_BASH=C:\Program Files\Git\bin\bash.exe"
"%CDXM_BASH%" -l "$shimBashPath" %*
"@

    New-Item -ItemType Directory -Force -Path $AgentsBin | Out-Null

    $refresh = $false
    if (Test-Path $ShimTarget) {
        $kind = Get-CodexEntrypointKind $ShimTarget
        if ($kind -eq 'codex-monitor') {
            # Already our shim: refresh in place (repairs a moved skill dir). No backup needed.
            $refresh = $true
        }
        else {
            # A foreign entrypoint (agmsg/custom) is installed. Reaching here means the
            # caller explicitly asked for the codex-monitor shim, so take over -- but keep
            # a timestamped backup so the previous entrypoint stays recoverable. A
            # conditional agmsg shim only app-server-binds projects whose delivery mode is
            # `monitor`, so it cannot guarantee cdxm a loaded thread; the codex-monitor
            # shim binds every interactive launch.
            if (-not (Confirm-CdxmStep "Replace existing '$kind' codex entrypoint at $ShimTarget with the codex-monitor shim (a backup will be kept)?" $true)) {
                Write-Host "Leaving existing codex entrypoint untouched at $ShimTarget (detected $kind)."
                Write-Host "  A conditional '$kind' shim may not make every interactive codex launch app-server-bound,"
                Write-Host "  so cdxm/codex-monitor may not find a loaded thread until the codex-monitor shim is installed."
                return
            }
            $stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
            $backup = "$ShimTarget.bak-$stamp"
            Copy-Item -Path $ShimTarget -Destination $backup -Force
            Write-Host "Backed up existing '$kind' codex entrypoint to $backup"
        }
    }

    Set-Content -Path $ShimTarget -Value $cmd -Encoding ASCII
    if ($refresh) {
        Write-Host "Refreshed existing codex-monitor shim at $ShimTarget"
    }
    else {
        Write-Host "Installed Codex monitor shim to $ShimTarget"
    }
    Write-Host "  routes through Git Bash to $shimSource"
}

function Add-UserPathEntry {
    param([string]$PathEntry)

    $current = [Environment]::GetEnvironmentVariable('Path', 'User')
    $parts = @()
    if ($current) {
        $parts = $current -split ';' | Where-Object { $_ }
    }
    if ($parts | Where-Object { $_ -ieq $PathEntry }) {
        Write-Host "PATH already contains $PathEntry"
        return
    }
    $newPath = if ($current) { "$PathEntry;$current" } else { $PathEntry }
    [Environment]::SetEnvironmentVariable('Path', $newPath, 'User')
    $env:Path = "$PathEntry;$env:Path"
    Write-Host "Added $PathEntry to the user PATH"
}

try {
    $SourceDir = Resolve-CdxmSource
    if (-not (Test-Path (Join-Path $SourceDir 'Cargo.toml'))) {
        throw "source does not look like codex-monitor: $SourceDir"
    }

    Write-Host 'codex-monitor Windows installer'
    Write-Host "source: $SourceDir"
    Write-Host "binary root: $InstallRoot"
    Write-Host "skill dir: $SkillDir"
    Write-Host "codex shim target: $ShimTarget"

    if (Confirm-CdxmStep "Install cdxm and codex-monitor binaries to $BinDir?" $true) {
        Install-CdxmBinaries $SourceDir
    } else {
        Write-Host 'Skipped binary install.'
    }

    if (Confirm-CdxmStep "Install Codex skill to $SkillDir?" $true) {
        Install-CdxmSkill $SourceDir
    } else {
        Write-Host 'Skipped skill install.'
    }

    $shouldInstallShim = $false
    if ($InstallShim) {
        $shouldInstallShim = $true
    } elseif ($NoShim) {
        $shouldInstallShim = $false
    } else {
        $shouldInstallShim = Confirm-CdxmStep "Install Codex shim at $ShimTarget?" $false
    }

    if ($shouldInstallShim) {
        Write-CdxmCodexCmd
    } else {
        Write-Host 'Skipped Codex shim install.'
    }

    if (-not $NoPath) {
        if (Confirm-CdxmStep "Add $BinDir and $AgentsBin to the user PATH?" $true) {
            Add-UserPathEntry $BinDir
            Add-UserPathEntry $AgentsBin
        } else {
            Write-Host 'Skipped PATH update.'
        }
    } else {
        Write-Host 'Skipped PATH update.'
    }

    Write-Host ''
    Write-Host 'Done.'
    Write-Host 'Open a new PowerShell window, then verify:'
    Write-Host '  Get-Command cdxm'
    Write-Host '  Get-Command codex -All'
} finally {
    if ($TempDir -and (Test-Path $TempDir)) {
        Remove-Item -Recurse -Force $TempDir
    }
}
